### ISSUE TITLE
Noetic package dependencies

### ISSUE THREAD

**Issue by sfalexrog** [machinekoder/ros_pytest#8]
Currently released Noetic package (http://packages.ros.org/ros/ubuntu/pool/main/r/ros-noetic-ros-pytest/) depends on both `python-pytest` and `python3-pytest`. My guess is that `python-pytest` is erroneously marked as a dependency, since ROS Noetic should work with Python 3 only.

This is probably due to older `bloom` utility. Please re-release using newer tooling, with no extra dependencies.

**Comment by jspricke** [comment]
@machinekoder can you fix this soon? (Also merge my PR please). Thanks!

**Comment by mikaelarguedas** [comment]
+1 merging #9 and rereleasing with bloom 9.0.0 or later would be greatly appreciated

**Comment by mikaelarguedas** [comment]
@machinekoder do you think we could get a new Noetic release now that #9 has been merged ?
Thanks!

**Comment by mikaelarguedas** [comment]
Happy new year @machinekoder !

Hope you're doing well.

Is there anything I can do to help getting a new release of ros_pytest in noetic ?

**Comment by mikaelarguedas** [comment]
@sloretz @tfoote This python2 dependency is still listed in the Noetic debs. Is there a way for OR or community members to make a debinc release of this package with a recent bloom to fix the dependency ?

Edit: Contacted the maintainer by email on 2021-04-17

**Comment by tfoote** [comment]
We don't have access or control of this package. Maybe @machinekoder would be willing to accept a volunteer to help maintain and make releases of this package or pass on maintenance if he's uninterested or unavailable.

**Comment by mikaelarguedas** [comment]
@machinekoder graciously gave me access and a new version has been tagged and release with the dependencies fixed https://github.com/ros/rosdistro/pull/29432
